### ISSUE TITLE
Where is the `json_page_generator.rb` file?

### ISSUE THREAD

**Issue by JimmyLv** [jgarber623/sixtwothree.org#44]
I want to implement the same functionality like this post mentioned, could you please help to provide more information about this?

https://sixtwothree.org/posts/adding-json-versions-of-posts-with-jekyll

**Comment by jgarber623** [comment]
@JimmyLv I've since migrated my site away from Jekyll, thus the broken link in that post. Here's the file you're looking for: https://github.com/jgarber623/sixtwothree.org/blob/b3891aff0ae15cf13005855f2488ced7d9e45e70/src/_plugins/json_page_generator.rb

**Comment by JimmyLv** [comment]
@jgarber623 Thank you very very much!
